// soth-node — JS shim layered on top of the napi-rs extension.
//
// The native extension exposes a low-level `SothSdk` class that returns
// typed `JsDecision` objects. This shim:
//   1. Exposes `init`, `guard`, `withContext` as the user-facing API
//   2. Translates `Decision::Block` into a thrown `SothBlocked`
//      (extends `Error`, NOT `OpenAI.APIError` / etc.)
//   3. Surfaces `Decision::Flag` via the `console.warn` channel and
//      a `SothFlagged` instance attached to the result for inspection
//
// Decision API contract: `docs/common/SDK_DECISION_API_SPEC.md` §6.3.
// The exception inheritance MUST stay flat — `SothBlocked extends Error`.
// If anyone changes that, `__test__/blocked-propagates.test.mjs` fails.

const { AsyncLocalStorage } = require('node:async_hooks');

// `binding.js` is auto-generated by `@napi-rs/cli` (via the
// `--js binding.js` flag in `package.json`). It contains the
// per-platform loader that resolves the right `.node` binary for
// the current host. Splitting it from this file keeps the
// hand-written shim — `init`, `guard`, `withContext`, `SothBlocked`
// — intact when `napi build` regenerates the loader.
const native = require('./binding.js'); /* eslint-disable-line global-require */

// Per-call context lives in AsyncLocalStorage so async functions
// awaited inside `withContext` see the same context after each await.
const _contextStore = new AsyncLocalStorage();

function _currentContext() {
  return _contextStore.getStore() ?? null;
}

/**
 * Run `fn` with per-call identity overrides applied to every
 * `guard()` / `guardStream()` inside it. Async-aware via
 * AsyncLocalStorage. Nested `withContext` calls merge — fields not
 * set in the inner block fall through to the outer block.
 *
 * `userIdHmac` MUST be the HMAC of the customer's user ID, computed
 * by the customer's code using their `SOTH_HMAC_KEY`. The SDK never
 * sees plaintext user IDs.
 */
async function withContext(overrides, fn) {
  const current = _contextStore.getStore() ?? {};
  const merged = { ...current };
  for (const k of ['userIdHmac', 'teamId', 'deviceIdHash', 'sessionId', 'requestId']) {
    if (overrides[k] !== undefined) merged[k] = overrides[k];
  }
  return _contextStore.run(merged, fn);
}

function _currentNativeContext() {
  const ctx = _currentContext();
  if (!ctx) return null;
  // napi-rs object key names match the Rust JsCallContext field
  // names (snake_case). The JS-facing helper uses camelCase for
  // ergonomics; we translate at the FFI boundary.
  return {
    userIdHmac: ctx.userIdHmac ?? null,
    teamId: ctx.teamId ?? null,
    deviceIdHash: ctx.deviceIdHash ?? null,
    sessionId: ctx.sessionId ?? null,
    requestId: ctx.requestId ?? null,
  };
}

class SothBlocked extends Error {
  constructor(decisionId, reason) {
    super(`SOTH policy blocked call: ${reason?.kind ?? 'unknown'}`);
    this.name = 'SothBlocked';
    this.decisionId = decisionId;
    this.reason = reason;
  }
}

class SothFlagged {
  constructor(severity) {
    this.severity = severity;
  }
}

let _singleton = null;

/**
 * Initialize the SOTH SDK module-level singleton.
 *
 * `hmacKeyEnv` / `hmacKeyStatic` are **optional in v1**. When neither
 * is set, customers pre-compute `userIdHmac` themselves (e.g. via
 * `crypto.createHmac('sha256', secret).update(userId).digest('hex')`)
 * and pass it through `withContext`, or omit user attribution.
 *
 * **Privacy tradeoff:** without an HMAC key, anything passed via
 * `userIdHmac` reaches soth-cloud as-is. Regulated workloads
 * (HIPAA / heavy-PII) SHOULD configure a key. The Phase-2.5 SDK
 * adds SDK-side hashing — see
 * `docs/common/SDK_WASM_TRUST_BOUNDARY_SPEC.md` §6.6.
 */
function init({ apiKey, orgId, hmacKeyEnv, hmacKeyStatic, telemetryEndpoint }) {
  if (!apiKey) throw new Error('init: apiKey required');
  if (!orgId) throw new Error('init: orgId required');
  _singleton = native.SothSdk.create(
    apiKey,
    orgId,
    hmacKeyEnv ?? null,
    hmacKeyStatic ?? null,
    telemetryEndpoint ?? null,
  );
}

/**
 * Stop the background telemetry shipper and flush pending events.
 * Customers SHOULD call this at process exit (e.g. on SIGINT / SIGTERM)
 * so the last batch window's events aren't lost. Idempotent.
 */
function shutdown() {
  if (_singleton) {
    _singleton.shutdown();
  }
}

function getSdk() {
  if (!_singleton) {
    throw new Error('soth.init({...}) must be called before any guard() / SDK call');
  }
  return _singleton;
}

async function guard(callFn, { call }) {
  const sdk = getSdk();
  const decision = sdk.preCall(call, _currentNativeContext());
  const { kind, token } = decision;

  if (kind === 'block') {
    sdk.postCall(token, null);
    throw new SothBlocked(token, decision.reason);
  }

  // Allow / Flag / Redact (Redact treated as Allow for v0; Phase-1
  // wires actual message rewriting via per-provider adapters).
  let result;
  try {
    result = await callFn();
  } finally {
    sdk.postCall(token, null);
  }

  if (kind === 'flag') {
    console.warn(`soth flagged call: severity=${decision.severity}`);
  }

  return result;
}

// Default chunk extractor for OpenAI-shaped chat-completion streams.
// Returns `{ deltaContent, finishReason }` extracted from the chunk's
// `choices[0]` entry. Customers using non-OpenAI shapes pass their own
// extractor to `guardStream`.
function defaultOpenAIChunkExtractor(chunk) {
  try {
    const choice = chunk?.choices?.[0];
    return {
      deltaContent: choice?.delta?.content ?? null,
      finishReason: choice?.finish_reason ?? null,
    };
  } catch (_) {
    return { deltaContent: null, finishReason: null };
  }
}

/**
 * Wrap a streaming LLM call with SOTH's pre/post lifecycle.
 *
 * `iterFactory` returns the provider's async iterable (e.g. the result
 * of `client.chat.completions.create({stream: true, ...})`). The
 * `chunkExtractor` (defaults to OpenAI shape) pulls
 * `{deltaContent, finishReason}` from each chunk; the SDK records
 * those alongside chunk count.
 *
 * Yields each chunk back to the caller. Throws `SothBlocked` if the
 * decision is `Block`. Always finalizes the stream observation on
 * normal completion or thrown exception.
 */
async function* guardStream(iterFactory, { call, chunkExtractor } = {}) {
  if (!call) throw new Error('guardStream: call required');
  const extractor = chunkExtractor ?? defaultOpenAIChunkExtractor;
  const sdk = getSdk();
  const decision = sdk.streamBegin(call, _currentNativeContext());
  const { kind, token } = decision;

  if (kind === 'block') {
    sdk.streamEnd(token);
    throw new SothBlocked(token, decision.reason);
  }

  let sequence = 0;
  try {
    let provIter = iterFactory();
    if (provIter && typeof provIter.then === 'function') {
      provIter = await provIter;
    }
    for await (const chunk of provIter) {
      const { deltaContent, finishReason } = extractor(chunk);
      sdk.streamChunk(token, sequence, deltaContent ?? null, finishReason ?? null);
      sequence += 1;
      yield chunk;
    }
  } finally {
    sdk.streamEnd(token);
  }
}

// Auto-instrumentation is loaded lazily so `require('@soth/sdk')`
// doesn't pull provider SDKs into the import graph until
// `instrument()` is actually called.
let _instrumentation = null;
function _getInstrumentation() {
  if (_instrumentation === null) {
    /* eslint-disable global-require */
    _instrumentation = require('./instrumentation/index.js');
    /* eslint-enable global-require */
  }
  return _instrumentation;
}

function instrument(opts) {
  return _getInstrumentation().instrument(opts);
}

function uninstrument(opts) {
  return _getInstrumentation().uninstrument(opts);
}

function isInstrumented(provider) {
  return _getInstrumentation().isInstrumented(provider);
}

module.exports = {
  init,
  shutdown,
  guard,
  guardStream,
  withContext,
  instrument,
  uninstrument,
  isInstrumented,
  getSdk,
  SothBlocked,
  SothFlagged,
};
